name: geofeed
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # 1. Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.1.0

  # 2. 상태 관리
  provider: ^6.1.2
  path_provider: ^2.1.3

  # 3. Media & EXIF
  image_picker: ^1.1.2
  exif: ^3.1.3
  flutter_image_compress: ^2.3.0

  # 4. Map & Clustering
  google_maps_flutter: 2.6.0
  google_maps_cluster_manager_2: ^3.2.0




  camera: ^0.10.5+9
  permission_handler: ^11.3.1
  geocoding: ^3.0.0
  google_sign_in: ^6.2.1

  # 5. Image Loader & Shimmer Effect
  cached_network_image: ^3.3.1        # ✔ CachedNetworkImage 추가
  shimmer: ^3.0.0                     # ✔ Shimmer 추가

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
